#! /bin/python

from pathlib import Path
import os
import libdnf5
import subprocess
import string



DICT_FILE = "repo"
TMP_FILE = "tmp"

def make_path(ENV_VAR: str, dir:str = None):
    try:
        appimage_dir = Path(os.environ[ENV_VAR])
    except:
        os.makedirs(dir , exist_ok=True)
        string = ENV_VAR + "=" + dir
        result = subprocess.run(["sudo", "echo", string, ">>" , "/etc/environment"], input="your_password\n", text=True)
        appimage_dir = Path(os.environ['APPIMAGE_DIR']) 
    return appimage_dir

def init_dnf():
    base = libdnf5.base.Base()
    base.load_config()
    base.setup()

    repo_sack = base.get_repo_sack()
    repo_sack.create_repos_from_system_configuration()
    repo_sack.load_repos()
    return base

# check if gh is installed:
def is_package_installed(base , package_name: str) -> bool:
    """Return True if a package is already installed."""
    query = libdnf5.rpm.PackageQuery(base)
    query.filter_name(package_name)
    query.filter_installed()
    return query.size() > 0





#! define paths 
HOME = os.environ['HOME']
config_dir = make_path('XDG_CONFIG_HOME', HOME+"/.config")
appimage_dir = make_path('APPIMAGE_DIR', HOME+"/.local/bin")

# move config_dir to the specific one
config_dir = config_dir / "appimageupdater"
config_dir.mkdir(exist_ok=True)


#! check if GITHUB cli is already installed
base = init_dnf()
if not is_package_installed(base , "gh"):
    raise EnvironmentError("install gh")




#! initialize repo -> package dict
# Each line in the file is in the format: <repo_url>=<package_name>=<version>
print("------------------ reading system appimages ----------------- ")
repos = {}
with open(str(config_dir / DICT_FILE)) as f:
    for raw_line in f:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("=")
        repo_url = parts[0].strip()
        package_name = parts[1].strip()
        version = parts[2].strip() if len(parts) > 2 else ""

        repos[repo_url] = {"name": package_name, "version": version}

needs_update = []
updatable_repos = {}

print("------------------ checking which files needs upgrade ----------------- ")
tmp_file = config_dir / TMP_FILE
if tmp_file.exists():
    tmp_file.unlink()
f = open(str(tmp_file), "w")
#! check if package needs update
for repo_url, package_info in repos.items():
    current_version = package_info["version"]
    latest_version = subprocess.run(["gh", "repo", "view", repo_url, "--json", "latestRelease", "--jq", ".latestRelease.tagName"], capture_output=True, text=True, check=True).stdout.strip()
    print(repo_url , "\t" , latest_version , "\t" , current_version)

    is_update_available = latest_version != current_version
    needs_update.append(is_update_available)
    if is_update_available:
        updatable_repos[repo_url] = {"name": package_info["name"],"latest": latest_version , "current": current_version}
    else:
        f.write(f"{repo_url}={package_info["name"]}={current_version}\n")
f.close()




print("------------------ updating single files ----------------- ")
f = open(str(config_dir / TMP_FILE) , "a+")
for repo_url, package_info in updatable_repos.items():
    latest_version = package_info["latest"]
    current_version = package_info["current"]
    package_name = package_info["name"]

    print(package_name)
    versionInName = latest_version.startswith("v") or current_version.startswith("v") or current_version in package_name

    old_eVersion = current_version
    new_eVersion = latest_version
    actual_name = package_name
    if versionInName:
        new_eVersion = latest_version[1:]
    if versionInName:
        old_eVersion = current_version[1:]

    if versionInName:
        package_name = package_name.replace(old_eVersion, new_eVersion)
        actual_name = package_name.replace(new_eVersion , "")

    subprocess.run(["gh", "release", "download", "--repo", repo_url, "--dir" , str(appimage_dir) , "--pattern", package_name , '--clobber'], capture_output=True, text=True, check=True)
    if versionInName:
        subprocess.run(["mv", str(appimage_dir /package_name), str(appimage_dir / actual_name)], check=True)
    f.write(f"{repo_url}={package_name}={latest_version}\n")


#! replace TMP_FILE with DICT_FILE and make everything executable
print("------------------ making everything executable ----------------- ")
subprocess.run(["mv", str(config_dir / TMP_FILE), str(config_dir / DICT_FILE)], check=True)
for repo_url, package_info in updatable_repos.items():
    package_name = package_info["name"]
    subprocess.run(["chmod", "+x", str(appimage_dir / package_name)], text=True)


        



    