#! /bin/bash

TV=HDMI-A-1
MONITOR=DP-2


disable(){
    if xrandr --query | grep $1; then
	    # DP-2 is connected/enabled — disable it
        echo "----------------$1---------------"
	    kscreen-doctor output.$1.disable
    fi
}

enable(){
    if ! xrandr --query | grep -q $1; then
	    # DP-2 is connected/enabled — disable it
        echo "----------------$1---------------"
	    kscreen-doctor output.$1.enable
    fi
}


if ! pgrep steam; then
    setsid steam >/dev/null 2>&1 </dev/null &
fi

enable "$TV"
disable "$MONITOR"



sleep 3
pactl set-default-sink alsa_output.pci-0000_03_00.1.hdmi-stereo-extra2

steam steam://open/bigpicture
